### ISSUE TITLE
Add stb_image.h and gtest as git submodules

### ISSUE THREAD

**Issue by VoidZeroNull0** [KittensBasket/PureSpace#5]
stb_image.h for loading texture images and gtest for tests.

**Comment by riogor** [comment]
Also consider moving these lines https://github.com/KittensBasket/PureSpace/blob/aa0d6c9abbf950d763619e7cc1417c53c73470c6/src/graphics.hpp#L9-L10 to a separate file (as described [in official documentation of stb](https://github.com/nothings/stb#how-do-i-use-these-libraries))

**Comment by VoidZeroNull0** [comment]
> Also consider moving these lines
> 
> https://github.com/KittensBasket/PureSpace/blob/aa0d6c9abbf950d763619e7cc1417c53c73470c6/src/graphics.hpp#L9-L10
> 
> to a separate file (as described [in official documentation of stb](https://github.com/nothings/stb#how-do-i-use-these-libraries))

Next time. Resolved with 9980e5878a9db61892102a34fdbdff9996dcbfdf
